# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 14:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0006_term_model_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtmModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(default=datetime.datetime.now)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTopicRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.Document')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.ArtmModel')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_model', models.IntegerField(default=0)),
                ('title', models.TextField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.ArtmModel')),
            ],
        ),
        migrations.CreateModel(
            name='TopTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.ArtmModel')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.Term')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='documenttopicrelation',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Topic'),
        ),
    ]
