# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20170112_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='id_model',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='topicintopic',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='models.Topic'),
        ),
        migrations.AlterField(
            model_name='topicintopic',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='models.Topic'),
        ),
    ]
