# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20170112_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='artmmodel',
            name='topics_count',
            field=models.TextField(null=True),
        ),
    ]
