# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_artmmodel_topics_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='spectrum_index',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
