# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_topic_spectrum_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='artmmodel',
            name='status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='artmmodel',
            name='status_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_short',
            field=models.TextField(null=True),
        ),
    ]
