# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20170115_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='title_multiline',
            field=models.TextField(null=True),
        ),
    ]
