# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_topic_title_multiline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='title_multiline',
        ),
    ]
