# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_remove_topic_title_multiline'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='documents_count',
            field=models.IntegerField(default=0),
        ),
    ]
