# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_topic_documents_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artmmodel',
            name='status_code',
        ),
        migrations.AlterField(
            model_name='artmmodel',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
