# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_remove_artmmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='artmmodel',
            name='status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='artmmodel',
            name='status_code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
