# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_artmmodel_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artmmodel',
            name='topics_count',
            field=models.TextField(default=''),
        ),
    ]
