# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_auto_20170119_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='artmmodel',
            name='polygon',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='documentintopic',
            name='polygon',
            field=models.TextField(null=True),
        ),
    ]
