# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0018_auto_20170119_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artmmodel',
            name='polygon',
        ),
        migrations.RemoveField(
            model_name='documentintopic',
            name='polygon',
        ),
    ]
