# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0019_auto_20170119_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='artmmodel',
            name='treshold',
            field=models.IntegerField(default=100),
        ),
    ]
