# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0022_auto_20170124_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentintopic',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
