# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 15:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artmmodel',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
