# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0006_term_model_id'),
        ('visual', '0002_artmmodel_creation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual.ArtmModel')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.Term')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual.Topic')),
            ],
        ),
    ]
