# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0003_topterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='topterm',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
