# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0005_documenttopicrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artmmodel',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='documenttopicrelation',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documenttopicrelation',
            name='model',
        ),
        migrations.RemoveField(
            model_name='documenttopicrelation',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='model',
        ),
        migrations.RemoveField(
            model_name='topterm',
            name='model',
        ),
        migrations.RemoveField(
            model_name='topterm',
            name='term',
        ),
        migrations.RemoveField(
            model_name='topterm',
            name='topic',
        ),
        migrations.DeleteModel(
            name='ArtmModel',
        ),
        migrations.DeleteModel(
            name='DocumentTopicRelation',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='TopTerm',
        ),
    ]
