# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 17:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0009_topic_documents_count'),
        ('visual', '0006_auto_20170110_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVisualization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='none')),
                ('status', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('finish_time', models.DateTimeField(null=True)),
                ('error_message', models.TextField(null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.ArtmModel')),
            ],
        ),
    ]
