# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0007_globalvisualization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalvisualization',
            name='error_message',
            field=models.TextField(default=''),
        ),
    ]
