# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0008_auto_20170118_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.TextField(null=True)),
                ('children', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
            ],
        ),
    ]
