# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0011_auto_20170121_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='children_placed',
            field=models.BooleanField(default=False),
        ),
    ]
