# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0013_auto_20170121_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='rect_height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='rect_left',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='rect_top',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='rect_width',
            field=models.FloatField(default=0),
        ),
    ]
